spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
spring.datasource.url: jdbc:mysql://localhost:3306/blog_engine
spring.datasource.username: root
spring.datasource.password:
spring.jpa.generate-ddl: true
spring.jpa.hibernate.ddl-auto: create

blog.title: DevPub
blog.subtitle: Мой блоговый движок
blog.phone: +7-995-595-66-82
blog.email: uskovvospb@gmail.com
blog.copyright: Усков Валерий
blog.copyrightFrom: 2022